services:
  redis:
    image: redis:7-alpine
    container_name: exchange-rate-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - exchange-rate-net
  app:
    build: .
    container_name: exchange-rate-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - exchange-rate-net
volumes:
  redis-data:
networks:
  exchange-rate-net:
    driver: bridge 